plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
}

group = 'com.toastcoders'
version = '9.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'com.toastcoders:yavijava:9.0-SNAPSHOT'
    implementation 'org.dom4j:dom4j:2.1.4'
    implementation 'javax.mail:mail:1.4.7'
    implementation 'javax.servlet:javax.servlet-api:3.1.0'
}
